### ISSUE TITLE
Create Trigger Feed failing with Check syntax errors message

### ISSUE THREAD

**Issue by mimy2001** [openwhisk/openwhisk-client-js#47]
Hi I'm trying the sample code:

create trigger feed from alarm package

// for example... 
const params = {cron: '*/8 * * * * *', trigger_payload: {name: 'James'}}
const name = '/whisk.system/alarms/alarm'
const trigger = 'alarmTrigger'
ow.feeds.create({name, trigger, params}).then(package => {
  console.log('alarm trigger feed created')
}).catch(err => {
  console.error('failed to create alarm trigger', err)
})

This is giving me a failure:
failed to create alarm trigger { BaseOperationError: Action invocation failed, API returned error code. Check syntax errors? Missing error message.
    at Client.handle_errors (/home/lzhao/openwhisk/code/openwhisk-package-ecs/node_modules/openwhisk/lib/client.js:102:13)
    at rp.catch.err (/home/lzhao/openwhisk/code/openwhisk-package-ecs/node_modules/openwhisk/lib/client.js:43:38)
    at tryCatcher (/home/lzhao/openwhisk/code/openwhisk-package-ecs/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._settlePromiseFromHandler (/home/lzhao/openwhisk/code/openwhisk-package-ecs/node_modules/bluebird/js/main/promise.js:510:31)
    at Promise._settlePromiseAt (/home/lzhao/openwhisk/code/openwhisk-package-ecs/node_modules/bluebird/js/main/promise.js:584:18)
    at Promise._settlePromises (/home/lzhao/openwhisk/code/openwhisk-package-ecs/node_modules/bluebird/js/main/promise.js:700:14)
    at Async._drainQueue (/home/lzhao/openwhisk/code/openwhisk-package-ecs/node_modules/bluebird/js/main/async.js:123:16)
    at Async._drainQueues (/home/lzhao/openwhisk/code/openwhisk-package-ecs/node_modules/bluebird/js/main/async.js:133:10)
    at Immediate.Async.drainQueues (/home/lzhao/openwhisk/code/openwhisk-package-ecs/node_modules/bluebird/js/main/async.js:15:14)
    at runCallback (timers.js:666:20)
    at tryOnImmediate (timers.js:639:5)
    at processImmediate [as _immediateCallback] (timers.js:611:5)
  name: 'BaseOperationError',
  message: 'Action invocation failed, API returned error code. Check syntax errors? Missing error message.',
  error:
   { duration: 109,
     name: 'alarm',
     subject: 'whisk.system',
     activationId: '20ae80ca53c24fa3886fb9a23e2ba16c',
     publish: false,
     annotations: [ [Object], [Object] ],
     version: '0.0.5',
     response: { result: [Object], success: false, status: 'application error' },
     end: 1492115313980,
     logs: [],
     start: 1492115313871,
     namespace: 'whisk.system' } }

Can you let me know why this is not working? I am able to use the sample snippets to create an action without any problems but I'm not able to do it for an alarm

**Comment by rabbah** [comment]
Is this an issue with the client or missing parameters to the feed? (@jasonpet FYI)

**Comment by mimy2001** [comment]
I'm just trying to test the sample code provided on the main page.  See full js file below (the commented out code works, I'm able to create the action without any problems, it's only the feed that doesn't work)  On the CLI i can also create the trigger no problem with the following command: 

$ wsk trigger create alarmTrigger --feed /whisk.system/alarms/alarm -p cron "*/8 * * * * *"  -i
ok: invoked /whisk.system/alarms/alarm with id b56f1dca40154827ba75610eff1ba335
{
    "activationId": "b56f1dca40154827ba75610eff1ba335",
    "annotations": [
        {
            "key": "limits",
            "value": {
                "logs": 10,
                "memory": 256,
                "timeout": 60000
            }
        },
        {
            "key": "path",
            "value": "whisk.system/alarms/alarm"
        }
    ],
    "duration": 62,
    "end": 1492120772615,
    "logs": [],
    "name": "alarm",
    "namespace": "whisk.system",
    "publish": false,
    "response": {
        "result": {},
        "status": "success",
        "success": true
    },
    "start": 1492120772553,
    "subject": "whisk.system",
    "version": "0.0.5"
}
ok: created trigger alarmTrigger

Here's my full javascript file: 

var fs = require('fs');
var openwhisk = require('openwhisk');

function action() {
   var options = {apihost: '172.17.0.1', api_key: '789c46b1-71f6-4ed5-8c54-816aa4f8c502:abczO3xZCLrMN6v2BKK1dXYFpXlPkccOFqm12CdAsMgRU4VrNZ9lyGVCGuMDGIwP',ignore_certs: true};
   var ow = openwhisk(options);

// for example...
const params = {cron: '*/8 * * * * *'}
const name = '/whisk.system/alarms/alarm'
const trigger = 'alarmTrigger'
ow.feeds.create({name, trigger, params}).then(package => {
  console.log('alarm trigger feed created')
}).catch(err => {
  console.error('failed to create alarm trigger', err)
});


//const actionName = 'pollAction'
//const action = fs.readFileSync('package.zip')
//ow.actions.create({actionName, action}).then(result => {
//  console.log('action created!')
//}).catch(err => {
//  console.error('failed to create action', err)
//})

}

action();

I also looked at the statusCode being returned and it's a 404 but i'm not sure why.  

Here's logs from the docker container (for a successful use case) : 
[2017-04-13T21:59:32.569Z] [INFO] [??] [alarmsTrigger] [POST /triggers] Got trigger {"name":"alarmTrigger","namespace":"_","cron":"*/8 * * * * *","payload":{"payload":""}}
[2017-04-13T21:59:32.574Z] [INFO] [??] [alarmsTrigger] [POST /triggers] Checking if user has access rights to create a trigger
**_[2017-04-13T21:59:32.590Z] [INFO] [??] [alarmsTrigger] [789c46b1-71f6-4ed5-8c54-816aa4f8c502] abczO3xZCLrMN6v2BKK1dXYFpXlPkccOFqm12CdAsMgRU4VrNZ9lyGVCGuMDGIwP https://172.17.0.1:443/api/v1/namespaces/_/triggers/alarmTrigger 200 user and password_**
[2017-04-13T21:59:32.592Z] [INFO] [??] [alarmsTrigger] [createTrigger] 789c46b1-71f6-4ed5-8c54-816aa4f8c502:abczO3xZCLrMN6v2BKK1dXYFpXlPkccOFqm12CdAsMgRU4VrNZ9lyGVCGuMDGIwP/_/alarmTrigger starting cron job
[2017-04-13T21:59:32.609Z] [INFO] [??] [alarmsTrigger] [POST /triggers] 789c46b1-71f6-4ed5-8c54-816aa4f8c502:abczO3xZCLrMN6v2BKK1dXYFpXlPkccOFqm12CdAsMgRU4VrNZ9lyGVCGuMDGIwP/_/alarmTrigger created successfully

For the one I'm invoking via code 👍 
2017-04-13T21:54:14.516Z] [INFO] [??] [alarmsTrigger] [POST /triggers] Got trigger {"name":"alarmTrigger","namespace":"_","cron":"*/8 * * * * *","payload":{"payload":""}}
[2017-04-13T21:54:14.517Z] [INFO] [??] [alarmsTrigger] [POST /triggers] Checking if user has access rights to create a trigger
**_[2017-04-13T21:54:14.539Z] [INFO] [??] [alarmsTrigger] [789c46b1-71f6-4ed5-8c54-816aa4f8c502] abczO3xZCLrMN6v2BKK1dXYFpXlPkccOFqm12CdAsMgRU4VrNZ9lyGVCGuMDGIwP https://172.17.0.1:443/api/v1/namespaces/_/triggers/alarmTrigger 404 user and password_**
[2017-04-13T21:54:14.540Z] [ERROR] [??] [alarmsTrigger] [POST /triggers] Trigger authentication request failed.

**Comment by mimy2001** [comment]
let me know if you need additional logs or information

**Comment by jthomas** [comment]
Have you already created the trigger (`alarmTrigger`) that this feed relies on? 

This error message is consistent with the feed referencing a trigger that does not exist. 

The error message returned is not helpful to understanding when this error occurs. We have an open issue (#45) to improve error messages returned from the API. I'll add this as an example to investigate. 

I'll update the README.md to clarify this dependency.

**Comment by mimy2001** [comment]
@jthomas Yes, I figured out the same thing later that day when I printed out the status code returned and tested some code to add a trigger first.  That's exactly what was wrong with my code.  I needed to create the trigger associated with my feed in my code first.  Thanks for your help.
